#!/bin/bash

#
# Download commandlinefu.com entries by page count
#
# Maintains state across invokations using a "start" file.  The start file
# contains the number of next page to request.  When this script was written
# there were about ~12400 entries in commandlinefu.com.
#
# Use this script to download one or more pages per execution, so we can read
# about 25 commands each day to improve our knowledge of unix/linux command
# line utilities.
#

#set -x

start=$1

if [ -z $start ]; then
  if [ -f ./start ]; then
    start=$(cat ./start)
  else
    start=0
  fi
fi

step=25
end=$(($start + $step))
page=$start

while [ $page -lt $end ]; do
    curl -s -o command-line-fu-$page.txt "http://www.commandlinefu.com/commands/browse/sort-by-votes/plaintext/$page";
    page=$(($page + $step))
done

echo "Downloaded todays command-line-fu page. Start reading at command-line-fu-$start.txt"

echo $end > start


